spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:test
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db.changelog/liquibase-changeLog.xml

#logging:
#  config: classpath:log4j2-spring.xml

server:
  error:
    include-message: always
  port: ${PORT:5000}


music-services:
  urlMap:
    APPLE: localhost:8080
    YANDEX: ${YANDEX_URL:noyandex}
    SPOTIFY: ${SPOTIFY_URL:nospotify}
  actionsMap:
    URL: ${GET_AUTH_URL:/authUrl}
    CODE: ${GET_AUTH_CODE:/register}
    EXPORT_PLAYLIST: ${EXPORT_PLAYLIST:/playlist}
    IMPORT_PLAYLIST: ${IMPORT_PLAYLIST:/test-synchronize-tracks}
    SEARCH_PLAYLIST: ${SEARCH_PLAYLIST:/playlistsList}
    REGISTER_YANDEX: ${REGISTER_YANDEX:/test-register}

